name: tik_tak_app
description: "A new way to waste your time!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rename_app: ^1.3.1
  video_player: ^2.8.3
  ## Run:
  ## dart run rename_app:main all="New App Name"
  ## to rename the app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/TikTakLogo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    # image_path: "path/to/image.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    # image_path: "path/to/image.png"
    # icon_size: 48 # min: 48, max: 256
  macos:
    generate: true
    # image_path: "path/to/image.png"

flutter:
  uses-material-design: true